/* eslint-disable */


import React, { Component, PropTypes } from 'react';
import Immutable from 'immutable';
import ListItem from './ListItem.js'
import axios from 'axios';


export default class Save extends Component {
  state = {
      value: null,
      playlistName: null,
      currentPlaylistID: null
  }

  updateInput(value) {
    this.setState(value);
  }

  handleSubmit() {
    this.props.toggleChecked(index);
  }

  handleDestroy(index) {
    this.props.deleteTodo(index);
  }

  addTracksToPlaylist() {
    const {uris} = this.props.tracks
    console.log(`props in adding to playlist: `, this.props)
    const at = localStorage.getItem('accessToken');
    const { currentPlaylistID } = this.state;
    console.log(`what are the URIS? : `, uris);
    const data = {
      "uris": uris
    }
    axios.post('https://api.spotify.com/v1/users/121636440/playlists/' + currentPlaylistID + '/tracks', data, {
      headers: {
        'Authorization': 'Bearer ' + at,
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      console.log('adding tracks to playlist ok?? : ', response);
    });
  }

  createAndSave() {
    const {playlistName} = this.state
    const at = localStorage.getItem('accessToken');
    const data = {
      "public": true,
      "name": playlistName,
      "description": "A playlist of songs sampled by kanye west. This playlist was generated by albert huynh's app"
    }

    axios.post('https://api.spotify.com/v1/users/121636440/playlists', data, {
      headers: {
        'Authorization': 'Bearer ' + at,
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      console.log('creating playlist ok?? : ', response);
      this.setState({ currentPlaylistID: response.data.id });
      this.addTracksToPlaylist();
    });
  }

  render() {
    console.log(`what is state in save: `, this.state)
    return (
      <div>
      <h3>Create Playlist</h3>
      <div>Playlist Name:<input value={this.state.playlistName} type="text" onChange={(event) => this.updateInput({playlistName: event.target.value})} /></div>
      <div><button className="btn btn-primary" onClick={() => this.createAndSave()}>Create</button></div>
    </div>
    );
  }
}

