/* eslint-disable */
import React, { Component, PropTypes } from 'react';
import { map } from 'ramda';
import Immutable from 'immutable';
import ListItem from './ListItem.js'
import axios from 'axios';

import styles from '../styles/app.scss';

export default class Save extends Component {
  state = {
      value: null,
      playlistName: null,
      currentPlaylistID: null
  }

  updateInput(value) {
    this.setState(value);
  }

  handleSubmit() {
    this.props.toggleChecked(index);
  }

  handleDestroy(index) {
    this.props.deleteTodo(index);
  }

  // Returns a list of URIs for each track in a users playlist. 
  getUris() {
    const {tracks} = this.props.tracks;
    return Object.values(map((track) => (track.uri), tracks));
  }

  // Adds all tracks in a users playlist into a newly created playlist
  addTracksToPlaylist() {
    const accessToken = localStorage.getItem('accessToken');
    const { currentPlaylistID } = this.state;
    const uris = this.getUris();
    const data = { uris };
    axios.post('https://api.spotify.com/v1/users/121636440/playlists/' + currentPlaylistID + '/tracks', data, {
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      console.log('adding tracks to playlist ok?? : ', response);
      // Create a success toast to notify user of successful creation
    });
  }

  // Creates a new playlist and then adds tracks to playlist on successful creation of playlist
  createAndSave() {
    const {playlistName} = this.state;
    const accessToken = localStorage.getItem('accessToken');
    const data = {
      "public": true,
      "name": playlistName,
      "description": "A playlist of songs sampled by kanye west. This playlist was generated by albert huynh's app"
    }
    axios.post('https://api.spotify.com/v1/users/121636440/playlists', data, {
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      console.log('creating playlist ok?? : ', response);
      this.setState({ currentPlaylistID: response.data.id });
      this.addTracksToPlaylist();
      // Create a success toast
    });
  }

  render() {
    return (
      <div className={`${styles.create__playlist }`}>
        <h2>Save Playlist</h2>
        <div>
          <input
            className={styles.save__input}
            value={this.state.playlistName}
            placeholder="What would you like to name your playlist?"
            type="text"
            onChange={(event) => this.updateInput({ playlistName: event.target.value })}
          />
          <button className="btn btn-primary" onClick={() => this.createAndSave()}>Save</button>
        </div>
    </div>
    );
  }
}

