/* eslint-disable */
import React, { Component, PropTypes } from 'react';
import { map } from 'ramda';
import { ToastContainer, toast } from 'react-toastify';

import ListItem from './ListItem.js'
import axios from 'axios';

import styles from '../styles/app.scss';

const darkToast = {
  className: { background: "black" },
  bodyClassName: "grow-font-size"
}


export default class Save extends Component {
  state = {
      value: null,
      playlistName: null,
      currentPlaylistID: null,
      saved: false
  }

  updateInput(value) {
    this.setState(value);
  }

  handleSubmit() {
    this.props.toggleChecked(index);
  }

  handleDestroy(index) {
    this.props.deleteTodo(index);
  }

  // Returns a list of URIs for each track in a users playlist. 
  getUris() {
    const {tracks} = this.props.tracks;
    return Object.values(map((track) => (track.uri), tracks));
  }

  // Adds all tracks in a users playlist into a newly created playlist
  addTracksToPlaylist() {
    const accessToken = localStorage.getItem('accessToken');
    const { currentPlaylistID } = this.state;
    const uris = this.getUris();
    const data = { uris };
    axios.post('https://api.spotify.com/v1/users/121636440/playlists/' + currentPlaylistID + '/tracks', data, {
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      // Create a success toast to notify user of successful creation
    });
  }

  // Creates a new playlist and then adds tracks to playlist on successful creation of playlist
  createAndSave() {
    const {searchedArtist} = this.props.search
    const {playlistName} = this.state;
    const accessToken = localStorage.getItem('accessToken');
    const data = {
      "public": true,
      "name": playlistName,
      "description": `A playlist of songs from artists ${searchedArtist} has sampled from. This playlist was generated by Albert Huynh's Who Sampled Playlist Spotify App :)`
    }
    axios.post('https://api.spotify.com/v1/users/121636440/playlists', data, {
      headers: {
        'Authorization': 'Bearer ' + accessToken,
        'Content-Type': 'application/json'
      }
    })
    .then(response => {
      this.setState({ currentPlaylistID: response.data.id });
      this.addTracksToPlaylist();
      // Create a success toast
      this.setState({saved: true})
      toast("Successfully created new playlist. Look for it in Spotify! 😎", darkToast)
    });
  }

  render() {
    return (
      <div className={`${styles.create__playlist }`}>
        <h2>Save Playlist</h2>
        <div>
          <input
            className={styles.save__input}
            value={this.state.playlistName}
            placeholder="What would you like to name your playlist?"
            type="text"
            onChange={(event) => {
              this.updateInput({ playlistName: event.target.value })
              this.setState({saved: false})
            }}
          />
          <button 
            className={styles.save__button}
            onClick={() => this.createAndSave()}> 
              {this.state.saved ? <span>Saved!</span> : <span>Save Playlist</span>}
          </button>
        </div>
        <ToastContainer />
    </div>
    );
  }
}

